### ISSUE TITLE
Deploy services from command line on the repository host

### ISSUE THREAD

**Issue by robin98sun** [robin98sun/sardines.shoal.js#2]
- [ ] generate temporary [service definition file] in memory
- [ ] generate temporary [service deploy plan file] in memory
- [x] modify [service_deployer].deploy method to accept deploy plan data in memory
- [ ] use [service_deployer] to deploy service
- [ ] copy test services from Dietitian project for test
